### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by SHEN1113** [aelbuni/distributed-byzantine-detection-algorithm#2]

**Comment by SHEN1113** [comment]
i want to learn about this project called [distributed-byzantine-detection-algorithm](https://github.com/aelbuni/distributed-byzantine-detection-algorithm)deeply, but i can not find the paper you wrote about it. Can you give me ? i will be appreciated for you kindness.

**Comment by aelbuni** [comment]
Hello Shen,

The official publication can be found here 

https://uwspace.uwaterloo.ca/handle/10012/11282

Thanks

**Comment by SHEN1113** [comment]
Thanks for your help.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "aelbuni/distributed-byzantine-detection-algorithm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月17日(星期四) 凌晨1:52
***@***.***&gt;;
抄送:&nbsp;"沈昕炎 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [aelbuni/distributed-byzantine-detection-algorithm] ask (Issue #2)





 
Hello Shen,
 
The official publication can be found here
 
https://uwaterloo.ca/electrical-computer-engineering/events/masc-seminar-abdurrahman-elbuni
 
Thanks
